# Removals

# Labyrinth staged hostile removal
[[remove]]
	dimension = 1024
	[remove.gamestage]
		gamestage = "cavern"

[[remove]]
	dimension = "-11325"
	[remove.gamestage]
		gamestage = "cavern"

[[remove]]
	[remove.entity]
		matcher = "demon_soldier"

[[remove]]
	group = "all"
	[remove.entity]
		mod = "aoa3"
	[remove.gamestage]
		gamestage = "advent"
		is_whitelist = false